version: '2.2'
services:
  estacionamentoapi:
    build:
      context: ./
      dockerfile: Dockerfile-build
    image: estacionamentoapi
    ports:
      - 8081:8080
    networks:
      - network1
    environment:
      - TZ=America/Sao_Paulo

networks:
  network1:
